### ISSUE TITLE
Report invalid hexastring in input seed or entropy as `EX_DATAERR = 65`

### ISSUE THREAD

**Issue by mvondracek** [mvondracek/PA193_mnemonic_Slytherin#52]
~~~
string argument   should contain only ASCII characters
Odd-length string
Non-hexadecimal digit found
~~~

Is currently reported as `UNKNOWN_FAILURE = 1`. Would be better to report it as `EX_DATAERR = 65` from `mnemoniccli.ExitCode.EX_DATAERR`.

**Comment by mvondracek** [comment]
Should wait until #41 gets merged.

**Comment by mvondracek** [comment]
@lsolodkova could you please take this?

**Comment by lsolodkova** [comment]
How can we unit-test non-Unicode entropy and seed? As far as I understand, if we generate entropy/seed in get_invalid_* function, we later open it in the same mode it was generated and written to file. And we write it (e.g., test_generate_invalid_entropy) in default UTF-8 (or not, since we do not specify the encoding).
