### ISSUE TITLE
Dictionary with word surrounded by whitespace is valid/invalid?

### ISSUE THREAD

**Issue by mvondracek** [mvondracek/PA193_mnemonic_Slytherin#59]
If a loaded dictionary contains correct number of words, which have correct length, but any line with word contains whitespaces before or after word, should the dictionary be considered valid or invalid?

Line 81 `line = next(f).strip()` ignores whitespace before and after word.

https://github.com/mvondracek/PA193_mnemonic_Slytherin/blob/420f3a5a8be8bf8a263c4053660993655bb2a9e2/PA193_mnemonic_Slytherin/mnemonic.py#L78-L89

**Comment by sobuch** [comment]
It is there to strip away '\n' from the words. If the dictionary is otherwise valid, whitespaces before or after the word will not change that(as they are stripped away), we can still proceed with such dictionary. Therefore, I suggest leaving this as is. Whitespaces inside the words would be a problem, but I believe that is already checked.
